export const users = [
  {
    id: 1,
    email: 'george.bluth@test.com',
    first_name: 'George',
    last_name: 'Bluth',
    avatar: 'https://reqres.in/img/faces/1-image.jpg',
    rating: 4,
    hobbies: ['Music', 'Photography'],
  },
  {
    id: 2,
    email: 'janet.weaver@test.com',
    first_name: 'Janet',
    last_name: 'Weaver',
    avatar: 'https://reqres.in/img/faces/2-image.jpg',
    rating: 3,
    hobbies: ['Dance', 'Programming'],
  },
  {
    id: 3,
    email: 'emma.wong@test.com',
    first_name: 'Emma',
    last_name: 'Wong',
    avatar: 'https://reqres.in/img/faces/3-image.jpg',
    rating: 5,
    hobbies: ['Cooking', 'Marathon'],
  },
  {
    id: 4,
    email: 'eve.holt@test.com',
    first_name: 'Eve',
    last_name: 'Holt',
    avatar: 'https://reqres.in/img/faces/4-image.jpg',
    rating: 2,
    hobbies: ['Gardening'],
  },
];
